const adminRoutes = require("./adminRoutes")
const companyRoutes = require("./companyRoutes")
const ledgerRoutes = require("./ledgerRoutes")
const exchangeRateRoutes = require("./exchangeRateRoutes")
const termsAndConditionsRoutes = require("./termsAndConditionsRoutes")
const contactMessageRoutes = require("./contactMessageRoutes")
const b2cRoutes = require("./b2cRoutes")
const companyCurrencyRoutes = require("./companyCurrencyRoutes")
const currencyRoutes = require("./currencyRoutes")
const bankCashAccountRoutes = require("./bankCashAccountRoutes")
const partnerRoutes = require("./partnerRoutes")
const taxRoutes = require("./taxRoutes")
const accessGroupRoutes = require("./accessGroupRoutes")
const userRoutes = require("./userRoutes")
const sidebarRoutes = require("./sidebarRoutes")
const protectedExampleRoutes = require("./protectedExampleRoutes")
const publicCountryRoutes = require("./publicCountryRoutes")
const portRoutes = require("./portRoutes")
const cabinRoutes = require("./cabinRoutes")
const payloadTypeRoutes = require("./payloadTypeRoutes")
const shipRoutes = require("./shipRoutes")
const priceListRoutes = require("./priceListRoutes")
const ticketingRuleRoutes = require("./ticketingRuleRoutes")

module.exports = (app) => {
  app.use("/api/public", publicCountryRoutes)
  app.use("/api/ports", portRoutes)
  app.use("/api/cabins", cabinRoutes)
  app.use("/api/payload-types", payloadTypeRoutes)
  app.use("/api/ships", shipRoutes)
  app.use("/api/exchange-rates", exchangeRateRoutes)
  app.use("/api/admin", adminRoutes)
  app.use("/api/companies", companyRoutes)
  app.use("/api/ledgers", ledgerRoutes)
  app.use("/api/companies", companyCurrencyRoutes)
  app.use("/api/currencies", currencyRoutes)
  app.use("/api/terms-and-conditions", termsAndConditionsRoutes)
  app.use("/api/contact-messages", contactMessageRoutes)
  app.use("/api/b2c", b2cRoutes)
  app.use("/api/bank-cash-accounts", bankCashAccountRoutes)
  app.use("/api/partners", partnerRoutes)
  app.use("/api/company/taxes", taxRoutes)
  app.use("/api/access-groups", accessGroupRoutes)
  app.use("/api/users", userRoutes)
  app.use("/api/sidebar", sidebarRoutes)
  app.use("/api/protected-example", protectedExampleRoutes)
  app.use("/api/price-lists", priceListRoutes)
  app.use("/api/ticketing-rules", ticketingRuleRoutes)
}
